-- +goose Up
ALTER TABLE media ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS mime_type TEXT;

-- +goose Down
ALTER TABLE media DROP COLUMN IF EXISTS url;
ALTER TABLE media DROP COLUMN IF EXISTS file_name;
ALTER TABLE media DROP COLUMN IF EXISTS file_size;
ALTER TABLE media DROP COLUMN IF EXISTS mime_type;
